### ISSUE TITLE
Nested Module Resolution?

### ISSUE THREAD

**Issue by Benno007** [Quramy/lerna-yarn-workspaces-example#8]
I'm trying to figure out how to get nested module resolution working with this project.

What I mean is modifying the structure to a more real-world example with multiple nested modules, in a domain driven architecture where all our exports are in a domain and referenced by e.g. `import { sleep } from '@quramy/x-core/messages/core'`

Structure:
```
- x-cli
-- src
--- main.ts
- x-core
-- src
--- messages
---- core
----- sleep
------ sleep.ts
------ sleep-and-snore.ts
------ index.ts
----- wake
------ wake.ts
------ wake-and-eat.ts
------ index.ts (exports wake and wake-and-eat)
```

I have modified `/tsconfig.json`: and then updated main.ts: 
```
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": "./packages",
    "paths": {
      "@quramy/x-core/messages/*": ["./x-core/src/messages/*"],
      "@quramy/*": ["./*/src"]
    }
  }
}
// main.ts (this works fine in the IDE, just doesn't build...)
import { sleep, sleepAndSnore } from '@quramy/x-core/messages/core'

export function cli() {
  sleep();
  sleepAndSnore()
  return Promise.resolve(true);
}
cli()

```

`yarn prepare` then gives me this error:
src/main.ts(1,38): error TS2307: Cannot find module '@quramy/x-core/messages/core'.

If I add the paths/baseUrl to the tsconfig.build.json, it will build, but it doesn't run because it can't find the module.

I also get the "source files not under the same rootDir message if I have that compilerOption set under this case: `TS6059: File '/home/bthompson/source/lerna-yarn-workspaces-example/packages/x-core/src/messages/core/index.ts' is not under 'rootDir' '/home/bthompson/source/lerna-yarn-workspaces-example/packages/x-cli/src'. 'rootDir' is expected to contain all source files.`

Any help would be greatly appreciated!

**Comment by osdiab** [comment]
I am also stuck wtih this same problem, did you come up wtih any solutions @Benno007 ?

**Comment by Benno007** [comment]
It was a tough one, but we ended up using a build step that used a makefile to run yarn build after `cd` into the package directory for each package (essentially `yarn --cwd packages/x-core build`), that way we got to use the tsconfig.build.json in each package, rather than the root level one. We couldn't ultimately use lerna in the same way this project does.

Our yarn workspaces were also setup a bit different, with our root package.json pointing to packages/*/dist (the compiled files of a package). We had a preinstall/postinstall for each packages/* package.json that created dist and copied e.g. packages/contracts/package.json into it's dist/ and the postinstall that symlinked the node modules up in packages/contracts (yarn workspaces would install in the dist directory due to packages/*/dist). This way we are able to import from @org/contracts/somewhere/somewhere from outside contracts, and from within contracts, used relative paths. It took a lot of fiddling, didn't think it would be that hard...

AFAIK there wasn't a simpler way to do it that was currently supported by lerna or yarn workspaces.

**Comment by osdiab** [comment]
For anyone who is also interested in this problem, now that Typescript 3 was released, there is a new feature called [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) that makes this a hell of a lot easier. I plan on shortly writing a blog post/opening a similar github repository as an example of how to set it up with `yarn workspaces`, but if anyone wants a reference for that right now, [this project of mine uses it](https://github.com/rahafoundation/raha-api).

**Comment by dgreene1** [comment]
@osdiab I’d be very interested in reading that blog article or seeing that template.

**Comment by osdiab** [comment]
I never wrote it but I’ll write something up in the next few days :)

**Comment by osdiab** [comment]
@dgreene1 Still working on it, should be out soon.

**Comment by xiaoyu-tamu** [comment]
> If I add the paths/baseUrl to the tsconfig.build.json, it will build, but it doesn't run because it can't find the module.

I solved this by using module-alias package.

```ts
import { addAlias } from 'module-alias';
import { join } from 'path';

if (process.env.NODE_ENV === 'development') {
  addAlias('@scope/common',  join(__dirname, '../../common/build'));
}
```
