### ISSUE TITLE
Build & watch all packages?

### ISSUE THREAD

**Issue by kachkaev** [Quramy/lerna-yarn-workspaces-example#9]
Hi @Quramy! 👋 

I'm curious how to `tsc --watch` all packages in parallel with one command? This can be useful if, say, my `packages/x-cli` needs to be linked and tested externally before everything is released. I'd like to be able to change `packages/x-core` and see the difference propagated to `x-cli` when I use it. Of course, there can be more than two packages in a monorepo, which makes it harder to run `tsc -w` in all subfolders one by one.

**Comment by Quramy** [comment]
Use “tsc -b”.

I’ve updated README and wrote this.
